server:
  servlet:
    context-path: /upload
  port: 8085

spring:
  application:
    # 应用名称
    name: upload
  servlet:
    multipart:
      # 启用
      enabled: true
      # 上传文件单个限制
      max-file-size: 10MB
      # 总限制
      max-request-size: 20MB
  mvc:
    static-path-pattern: /xxx/**
  resources:
    static-locations: classpath:/images


upload:
  directory: \upload
